apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: LoadBanlancer
  ports:
  - port: 80
  #5001
    name: result-service
    targetPort: 80
    #nodePort: 31001
  selector:
    app: result    
