apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: LoadBanlancer
  ports:
  - port: 80
  #5000
    name: vote-service
    targetPort: 80
    #nodePort: 31000
  selector:
    app: vote    
