apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-app
    type: backend
spec:
  template:
    metadata:
      name: backend-container
      labels:
        app: backend-app
        type: backend
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      type: backend
  replicas: 2                
