apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: musql-app
spec:
  containers:
    - name: mysql-container
      image: mysql:5.6
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: geek
#10.244.0.8
#10.96.0.10